import express from "express";
import multer from "multer";
import userController from "../controllers/userController";
const router = express.Router({ mergeParams: true });
const upload = multer();
router.get("/", userController.getUser);
router.put("/", upload.any(), userController.editUser);
router.delete("/", userController.deleteUser);
router.get("/friend-requests", userController.getFriendRequests);
router.post("/friend-requests", userController.addFriendRequest);
router.put("/friend-requests", userController.setFriendRequestsAsViewed);
router.get("/friends", userController.getFriends);
router.delete("/friends/:friendId", userController.deleteFriend);
router.post("/friends/:friendId", userController.acceptFriendRequest);
export default router;
